# Generated by Django 3.1.2 on 2021-04-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contectme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contecthere',
            name='phone',
            field=models.IntegerField(default=None),
        ),
    ]
