# Generated by Django 3.1.2 on 2021-04-22 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
