# Generated by Django 3.1.2 on 2021-04-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0004_youtuber_sub_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='sub_count',
            field=models.CharField(default='', max_length=255),
        ),
    ]
